#7 Update change logs
nish-kishore/tidypolis pull request #17
Opened 2024-01-24 22:19 UTC by Heaghneyn

2024-01-31 20:15 UTC, Heaghneyn commented
- [ ] add logging of new viruses and new circulating

2024-02-01 18:00 UTC, nish-kishore commented on R/utils.R
> +                             .event_type = "START",
You could leave the default value empty which would force people to put in an event type ever time. That way we don't have accidental "START" entries

2024-02-01 18:02 UTC, Heaghneyn commented on R/utils.R
> +                             .event_type = "START",
but don't we not want people to put in values since this is all supposed to run behind the scenes?

2024-02-01 18:02 UTC, nish-kishore commented on R/utils.R
> +        .event_type = "START"
I think this should be a "PROCESS" since we are using "START" and "END" exclusively to identify full runs

2024-02-13 18:24 UTC, nish-kishore requested changes
Awesome work, some very minor comments. Let me know if you want to chat about it

2024-02-13 18:24 UTC, nish-kishore commented on R/utils.R
> +  if(dir.exists(file.path(polis_data_folder, "Log_Archive")) == FALSE){
Not something you need to change but I'd prefer our standard to stop testing booleans. So `dir.exists` returns a boolean so you can just do `!dir.exists()` to get the opposite, I can make the edits for now

2024-02-13 18:24 UTC, nish-kishore commented on R/utils.R
> +  afp.files.01 <- list.files(path = paste0(polis_data_folder, "/Core_Ready_Files/"), pattern = "^(afp_linelist_2001-01-01_2024).*(.rds)$", full.names = TRUE)
Let's change this to be more dynamic in naming 2024. Otherwise we'll have to dig and find this every time...

2024-02-13 20:11 UTC, Heaghneyn commented on R/init.R
> +
added end for pop download

[eb305ac](https://github.com/nish-kishore/tidypolis/pull/17/commits/eb305ac3cd64777a94778471c7604d2917f5e78e)

2024-02-13 20:13 UTC, Heaghneyn commented on R/utils.R
> +  if(dir.exists(file.path(polis_data_folder, "Log_Archive")) == FALSE){
fixed double call to boolean

[afa5603](https://github.com/nish-kishore/tidypolis/pull/17/commits/afa5603652edcb33ec47363da614e948f74e97c7)

2024-02-13 20:15 UTC, nish-kishore approved these changes

2024-02-13 20:15 UTC, merged