Fully local preprocessing
nish-kishore/tidypolis pull request #44
Opened 2024-04-09 16:45 UTC by Heaghneyn

- [x]  reconcile case counts (pre-2020) for static files, preprocessed new data and POLIS -> need input from team
- [x] address "MULTIPOLYGON EMPTY" shapes in shape file

potentially need to recreate static pre-2020 files

2024-04-23 15:10 UTC, Heaghneyn commented
- [ ] removing "local" option to preprocessing, instead changing afp preprocessing to full table (2001 - present) every time

2024-04-23 16:54 UTC, Heaghneyn commented
closes #32

2024-04-23 17:26 UTC, nish-kishore requested changes
Need to convert all `load_clean_{spatial}_sp` into `tidypolis_io` so that Mo can run locally, current instances found on lines: 
- 1520
- 2566
- 3712

2024-05-17 15:10 UTC, Heaghneyn commented
closes #44

2024-05-17 15:12 UTC, Heaghneyn reviewed
requested changes addressed and SIA data completed

2024-05-17 17:55 UTC, Heaghneyn commented
- [ ] update references to old files
- [ ] remove calls to "core files to combine" and update tidypolis_io writes in AFP and SIA

2024-06-20 16:53 UTC, mcuadera approved these changes

2025-04-15 17:58 UTC, mcuadera commented
@Heaghneyn is this branch stale?

2025-04-22 12:29 UTC, closed without merging