:bug: added in error catching for f.pre.st_sample
nish-kishore/tidypolis pull request #50
Opened 2024-05-03 17:36 UTC by nish-kishore

If geometry is erroneous, it creates a small circular polygon in the center of the geometry and samples from that

2024-05-06 14:14 UTC, Heaghneyn requested changes
@mcuadera in the warning listing the districts being fixed the guids are mis-assigned

adm0 = Country, adm1 = Province, adm2 = District

2024-05-07 15:06 UTC, mcuadera commented
added fix for misassigned names

2024-05-07 15:07 UTC, mcuadera approved these changes

2024-05-07 15:26 UTC, Heaghneyn approved these changes

2024-05-08 16:59 UTC, Heaghneyn requested changes
starting at line 1101, the prov_name object should be renamed to something like dist_name or ctry_prov_dist_name to better represent what it is and the select should include adm2name

2024-05-14 14:10 UTC, Heaghneyn approved these changes

2024-05-17 17:47 UTC, merged